version: 1.0.{build}

platform:
- Win32

environment:
  matrix:
    - compiler: mingw

install:
- cd ..
- appveyor DownloadFile http://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
- 7z x .\WpdPack_4_1_2.zip -oc:\
- set PATH=%PATH%;C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin

before_build:
- cd C:\projects\PcapPlusPlus
- configure-windows.bat -m C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32 -s C:\msys64 -w C:\WpdPack

build_script:
- mingw32-make all

test_script:
- cd C:\projects\PcapPlusPlus\Packet++Test
- Bin\Packet++Test.exe